spring:
  application:
    name: ${artifactId}
  profiles:
    active: #{ENV:dev}
  datasource:
    url: #{DB_URL:jdbc:postgresql://localhost:5432/test_db}
    username: #{DB_USER:root}
    password: #{DB_PASSWORD:12345}
    database: #{DB_DATABASE:test_db}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  jackson:
    deserialization:
      fail-on-unknown-properties: true
server:
  error:
    include-message: always